### ISSUE TITLE
License uncertainity

### ISSUE THREAD

**Issue by gleber** [fpco/stackage-view#14]
Currently LICENSE file suggests this is a software whose source code is available, but not licensed under any open source license. This makes it impossible to use by anyone who's conscious about  licensing of their code. If possible, please select a widely used and court-battle-tested open source license.

**Comment by snoyberg** [comment]
I'm afk right now so can't update, but I'm declaring the code licensed
under the MIT license. If someone wants to send a PR to reflect this, I'll
merge. Otherwise, I'll update next week.

**Comment by gleber** [comment]
@snoyberg PR sent

**Comment by snoyberg** [comment]
Thanks!
