### ISSUE TITLE
ghcjs-dev image not on docker

### ISSUE THREAD

**Issue by silky** [fpco/stackage-view#16]
```
04:03 PM noon ∈ stackage-view@master>stack docker pull                                    ▲▲▲ 
Pulling image from registry: 'fpco/ghcjs-dev:lts-2.13'
Pulling repository docker.io/fpco/ghcjs-dev
Error: image fpco/ghcjs-dev:lts-2.13 not found
Could not pull Docker image:
    fpco/ghcjs-dev:lts-2.13
There may not be an image on the registry for your resolver's LTS version in
your configuration file.
```

**Comment by mgsloan** [comment]
It'd probably be best to update stackage-view to use stack's ghcjs support, which wasn't around when it was written.

Also, stackage-view isn't being developed, and we don't have plans to continue development.

**Comment by silky** [comment]
okay; if it's not being developed that's fine. i was just attempting to build the project when i noticed it didn't build as-is (without this docker image)
